// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBrbD3WWeqvpxARvpSYxukR6bJl_lsRbA',
    appId: '1:344547215844:web:e0366ec62939ffe2dddff1',
    messagingSenderId: '344547215844',
    projectId: 'instagram-clone-0x45',
    authDomain: 'instagram-clone-0x45.firebaseapp.com',
    storageBucket: 'instagram-clone-0x45.appspot.com',
    measurementId: 'G-WS445VSWPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQqI80nT507vcpqlM6XTydFJThC_pLw_0',
    appId: '1:344547215844:android:0ed744ac93908429dddff1',
    messagingSenderId: '344547215844',
    projectId: 'instagram-clone-0x45',
    storageBucket: 'instagram-clone-0x45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpkwa2P4kYNSofcOwsI7TtJCgLDAcYlJU',
    appId: '1:344547215844:ios:bcfda2d63a16c3ebdddff1',
    messagingSenderId: '344547215844',
    projectId: 'instagram-clone-0x45',
    storageBucket: 'instagram-clone-0x45.appspot.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
